Update hello.yml

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -25,5 +25,5 @@ jobs:
 
       - name: Show runner operating system
         run: echo "Running on $RUNNER_OS"
-      - name: Fail step
-        run: exit 1
+     # - name: Fail step
+      #  run: exit 1
